import { getUserMessage, getLoadingType } from "./general";
import {
  PHARMACY,
  CLINIC,
  MEDICAL,
  HOSPITAL,
  PRODUCTION_AUTH_ENDPOINT,
  LOCAL_AUTH_ENDPOINT,
  PRODUCTION_SEARCH_ENDPOINT,
  LOCAL_SEARCH_ENDPOINT,
} from "./constants";

export {
  getUserMessage,
  getLoadingType,
  PHARMACY,
  CLINIC,
  MEDICAL,
  HOSPITAL,
  PRODUCTION_SEARCH_ENDPOINT,
  PRODUCTION_AUTH_ENDPOINT,
  LOCAL_AUTH_ENDPOINT,
  LOCAL_SEARCH_ENDPOINT,
};
